DROP TABLE IF EXISTS film, Mpa, Likes, Genre, Genre_list, User_filmorate, Friends, Directors, Film_director, Reviews, Film_reviews CASCADE;

CREATE TABLE IF NOT EXISTS Film (
  unit_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name_film varchar NOT NULL,
  description_film varchar,
  releaseDate_film date NOT NULL,
  duration_film integer NOT NULL,
  mpa_id integer
);

CREATE TABLE IF NOT EXISTS Mpa (
  mpa_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name_mpa varchar NOT NULL,
  description_mpa varchar
);

CREATE TABLE IF NOT EXISTS Likes (
  user_id integer NOT NULL,
  film_id integer NOT NULL
);

CREATE TABLE IF NOT EXISTS Genre (
  genre_id integer NOT NULL,
  film_id integer NOT NULL
);

CREATE TABLE IF NOT EXISTS Genre_list (
  generelist_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  description_genre varchar NOT NULL
);

CREATE TABLE IF NOT EXISTS User_filmorate (
  user_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email_user varchar NOT NULL,
  login_user varchar NOT NULL,
  name_user varchar NOT NULL,
  birthday_user date
);

CREATE TABLE IF NOT EXISTS Friends (
  friends_id integer NOT NULL,
  user_id integer NOT NULL,
  friendship_status BOOLEAN NOT NULL default false
);

CREATE TABLE IF NOT EXISTS Reviews (
    review_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content VARCHAR NOT NULL,
    is_positive BOOLEAN NOT NULL,
    user_id BIGINT NOT NULL,
    film_id BIGINT NOT NULL,
    useful INTEGER NOT NULL
    );

CREATE TABLE IF NOT EXISTS Film_reviews (
    review_id INTEGER NOT NULL,
    user_id BIGINT NOT NULL,
    is_like BOOLEAN NOT NULL,
    PRIMARY KEY (review_id, user_id)
    );

CREATE TABLE IF NOT EXISTS Directors (
  director_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name_director varchar NOT NULL
);

CREATE TABLE IF NOT EXISTS Film_director (
  film_id integer NOT NULL,
  director_id integer NOT NULL
);

ALTER TABLE Film ADD FOREIGN KEY (mpa_id) REFERENCES Mpa (mpa_id) ON DELETE CASCADE;

ALTER TABLE Film_director ADD FOREIGN KEY (film_id) REFERENCES Film (unit_id) ON DELETE CASCADE;

ALTER TABLE Film_director ADD FOREIGN KEY (director_id) REFERENCES Directors (director_id) ON DELETE CASCADE;

ALTER TABLE Likes ADD FOREIGN KEY (user_id) REFERENCES User_filmorate (user_id) ON DELETE CASCADE;

ALTER TABLE Likes ADD FOREIGN KEY (film_id) REFERENCES Film (unit_id) ON DELETE CASCADE;

ALTER TABLE Genre ADD FOREIGN KEY (genre_id) REFERENCES Genre_list (generelist_id) ON DELETE CASCADE;

ALTER TABLE Genre ADD FOREIGN KEY (film_id) REFERENCES Film (unit_id) ON DELETE CASCADE;

ALTER TABLE Friends ADD FOREIGN KEY (friends_id) REFERENCES User_filmorate (user_id) ON DELETE CASCADE;

ALTER TABLE Friends ADD FOREIGN KEY (user_id) REFERENCES User_filmorate (user_id) ON DELETE CASCADE;

ALTER TABLE Reviews ADD FOREIGN KEY (user_id) REFERENCES User_filmorate (user_id) ON DELETE CASCADE;

ALTER TABLE Reviews ADD FOREIGN KEY (film_id) REFERENCES Film (unit_id) ON DELETE CASCADE;

ALTER TABLE Film_reviews ADD FOREIGN KEY (review_id) REFERENCES Reviews (review_id) ON DELETE CASCADE;

ALTER TABLE Film_reviews ADD FOREIGN KEY (user_id) REFERENCES User_filmorate (user_id) ON DELETE CASCADE;

CREATE UNIQUE INDEX IF NOT EXISTS user_filmorate_id_uindex ON User_filmorate (user_id);

CREATE UNIQUE INDEX IF NOT EXISTS film_id_uindex ON Film (unit_id);

CREATE UNIQUE INDEX IF NOT EXISTS mpa_id_uindex ON Mpa (mpa_id);

CREATE UNIQUE INDEX IF NOT EXISTS genre_list_id_uindex ON Genre_list (generelist_id);